disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Aleksandar Zizovic"

[params]
  [params.homepage]
    layout = "list"
    showRecent = true
    mainSections = ["projects"]
    recentLimit = 3

  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Personal portfolio site"
  copyright = "© 2025 Aleksandar Zizovic"

[params.author]
  image = "img/profile-photo.jpg"
  imageQuality = 96
  headline = "Hi, I’m Aleksandar - a Backend Developer based in Belgrade, Serbia.  Passionate about clean code, distributed systems, and solving real-world challenges.</b>"

